@baseUrl=http://localhost:3000
@accessTokenName=access-token
@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU2OTYwMzE5LCJleHAiOjE3NTY5NjM5MTl9.b-nEcwF--RqUp4F8KYPb6W6wzL9O5qUWekp3_uxSiq8
@refreshTokenName=refresh-token
@refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU2OTYwMzE5LCJleHAiOjE3NTcwNDY3MTl9.fH188Npr22DwNui966SZqgFjB_XgnYyCYbTBFunAjD4
@productId=2
@articleId=
### 회원가입
POST {{baseUrl}}/users/register
Content-Type: application/json

{
    "email": "test@test.com",
    "nickname": "tester",
    "password": "password"
}

### 로그인
POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "password"
}

### 로그아웃
POST {{baseUrl}}/users/logout
Cookie: {{accessTokenName}}={{accessToken}}

### 상품 등록
POST {{baseUrl}}/products
Cookie: {{accessTokenName}}={{accessToken}}
Content-Type: application/json

{
    "name":"Test_Product",
    "description":"Test_Description",
    "price":10000,
    "tags":["test_tag"]
}

### 상품 수정
PATCH {{baseUrl}}/products/{{productId}}
Cookie: {{accessTokenName}}={{accessToken}}
Content-Type: application/json

{
    "name":"Updated_Test_Product"
}

### 상품 덧글 작성
POST {{baseUrl}}/products/comments/{{productId}}
Cookie: {{accessTokenName}}={{accessToken}}
Content-Type: application/json

{
    "content":"Test_Comment"
}

###상품 삭제
DELETE {{baseUrl}}/products/{{productId}}
Cookie: {{accessTokenName}}={{accessToken}}

### 게시글 등록
POST {{baseUrl}}/articles
Cookie: {{accessTokenName}}={{accessToken}}
Content-Type: application/json

{
    "title":"Test_Article",
    "content":"Test_Content"
}

### 게시글 수정
PATCH {{baseUrl}}/articles/1
Cookie: {{accessTokenName}}={{accessToken}}
Content-Type: application/json

{
    "title":"Updated_Test_Article"
}

### 게시글 덧글 작성
POST {{baseUrl}}/articles/comments/2
Cookie: {{accessTokenName}}={{accessToken}}
Content-Type: application/json

{
    "content":"Test_Comment"
}


### 게시글 삭제
DELETE {{baseUrl}}/articles/1
Cookie: {{accessTokenName}}={{accessToken}}


### 유저 프로필 조회
GET {{baseUrl}}/users/profile
Cookie: {{accessTokenName}}={{accessToken}}


### 토큰 갱신
GET {{baseUrl}}/users/refresh
Cookie: {{refreshTokenName}}={{refreshToken}}

### 상품 좋아요
POST {{baseUrl}}/products/likes/{{productId}}
Cookie: {{accessTokenName}}={{accessToken}}

### 상품 좋아요 목록 받기
GET {{baseUrl}}/products/likes
Cookie: {{accessTokenName}}={{accessToken}}
