

const ACCESS_SECRET_KEY = qwer; 
const REFRESH_SECRET_KEY = asdf;
const JWS_SECRET_KEY = zxcv;
const ACCESS_TOKEN_COOKIE_NAME = qwer;
const REFRESH_TOKEN_COOKIE_NAME = asdf;

export {
    ACCESS_SECRET_KEY,
    REFRESH_SECRET_KEY,
    JWS_SECRET_KEY
}