-- =========================
-- 1. USERS 테이블
-- =========================
CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar(255) UNIQUE NOT NULL,
  "nickname" varchar(50) NOT NULL,
  "image" varchar(255),
  "password" varchar(255) NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

-- =========================
-- 2. ARTICLES 테이블
-- =========================
CREATE TABLE "articles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(255) NOT NULL,
  "content" text NOT NULL,
  "image" varchar(255),
  "user_id" int NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);


-- =========================
-- 3. PRODUCTS 테이블
-- =========================
CREATE TABLE "products" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "description" text NOT NULL,
  "price" int NOT NULL,
  "thumbnail" varchar(255),
  "user_id" int NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);


-- =========================
-- 4. PRODUCT_IMAGES 테이블
-- =========================
CREATE TABLE "product_images" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "url" varchar(255) NOT NULL,
  "order" int,
  "product_id" int NOT NULL,
  "created_at" timestamp DEFAULT (now())
);


-- =========================
-- 5. COMMENTS 테이블
-- =========================
CREATE TABLE "comments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "content" text NOT NULL,
  "product_id" int,
  "article_id" int,
  "user_id" int,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);


-- =========================
-- 6. FAVORITES 테이블
-- =========================
CREATE TABLE "favorites" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int NOT NULL,
  "user_id" int NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);


-- =========================
-- 7. LIKES 테이블
-- =========================
CREATE TABLE "likes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "article_id" int NOT NULL,
  "user_id" int NOT NULL,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);


-- =========================
-- 8. TAGS 테이블
-- =========================
CREATE TABLE "tags" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) UNIQUE NOT NULL
);


-- =========================
-- 9. PRODUCT_TAGS 테이블
-- =========================
CREATE TABLE "product_tags" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" int NOT NULL,
  "tag_id" int NOT NULL
);


-- =========================
-- 인덱스 및 외래키 설정
-- =========================
CREATE INDEX ON "users" ("email");
CREATE INDEX ON "articles" ("user_id");
CREATE INDEX ON "products" ("user_id");
CREATE INDEX ON "product_images" ("product_id");
CREATE INDEX ON "comments" ("product_id");
CREATE INDEX ON "comments" ("article_id");
CREATE INDEX ON "comments" ("user_id");
CREATE INDEX ON "favorites" ("product_id");
CREATE INDEX ON "favorites" ("user_id");
CREATE INDEX ON "likes" ("article_id");
CREATE INDEX ON "likes" ("user_id");
CREATE INDEX ON "product_tags" ("product_id");
CREATE INDEX ON "product_tags" ("tag_id");

ALTER TABLE "articles" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "products" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "product_images" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id") ON DELETE CASCADE;
ALTER TABLE "comments" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id") ON DELETE CASCADE;
ALTER TABLE "comments" ADD FOREIGN KEY ("article_id") REFERENCES "articles" ("id") ON DELETE CASCADE;
ALTER TABLE "comments" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "favorites" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id") ON DELETE CASCADE;
ALTER TABLE "favorites" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "likes" ADD FOREIGN KEY ("article_id") REFERENCES "articles" ("id") ON DELETE CASCADE;
ALTER TABLE "likes" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "product_tags" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id") ON DELETE CASCADE;
ALTER TABLE "product_tags" ADD FOREIGN KEY ("tag_id") REFERENCES "tags" ("id") ON DELETE CASCADE;


-- =========================
-- 트리거: updated_at 자동 갱신
-- =========================

-- 1️⃣ 공통 함수 생성 (모든 테이블에 사용)
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 2️⃣ 트리거 생성 (updated_at 있는 테이블 전부)
CREATE TRIGGER update_users_updated_at
BEFORE UPDATE ON "users"
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_articles_updated_at
BEFORE UPDATE ON "articles"
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_products_updated_at
BEFORE UPDATE ON "products"
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_comments_updated_at
BEFORE UPDATE ON "comments"
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_favorites_updated_at
BEFORE UPDATE ON "favorites"
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_likes_updated_at
BEFORE UPDATE ON "likes"
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
