POST  http://localhost:3000/register
Content-Type: application/json

{
  "email": "chicken@example.com",
  "nickname": "chickenLover",
  "password": "password1123"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "chicken@example.com",
  "password": "password1123"
}
