name: CI (Test)

on:
  pull_request:
    branches: [ "main", "develop", "feature/*", "김지헌-sprint11" ]

jobs:
  test:
    runs-on: ubuntu-latest

   
    defaults:
      run:
        working-directory: ./mission-11
    

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Generate Prisma Client
      run: npx prisma generate

    - name: Run Tests
      run: npm test
      # 테스트 통과를 위해 가짜 환경변수 주입 (env.validation 통과용)
      env:
        DATABASE_URL: "postgresql://test:test@localhost:5432/test"
        JWT_SECRET_KEY: "test-secret"
        JWT_REFRESH_SECRET_KEY: "test-refresh-secret"
        PORT: 3000