name: 🧪 Run Tests on Pull Request

on:
  pull_request:
    branches:
      - '*' # 모든 브랜치에서 PR 발생 시 동작

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      
      - name: Generate Prisma Client
        run: yarn prisma generate

      - name: Run unit tests
        run: yarn test 
